# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prueba',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
